### ISSUE TITLE
Bug in adrift.pl Line 1755 : non-existent subroutine (incorrectly named)

### ISSUE THREAD

**Issue by AeonBlack** [FictitiousFrode/Decompilers#2]
Was:

`1755:			 writeXMLElement('Person', Person( $Objects[$object]{Parent} )); `

Assuming:

`1755:			 writeXMLElement('Person', namePerson( $Objects[$object]{Parent} )); `

**Comment by FictitiousFrode** [comment]
Thanks, fixed :)
